sudo: false # http://docs.travis-ci.com/user/workers/container-based-infrastructure/
language: node_js
node_js:
  - 4

notifications:
  email:
    - medikoo+html-template-to-dom@medikoo.com

script: "npm test && npm run lint"
